const LinkedList = require('./ll')

describe('Singly Linked List', () => {
  test('append', () => {
    const ll = new LinkedList()
    ll.append(10)
    ll.append('10')
    ll.append('ten')
    expect(ll.head.value).toEqual(10)
    expect(ll.tail.value).toEqual('ten')
    expect(ll.size).toEqual(3)
  })
  test('prepend', () => {
    const ll = new LinkedList()
    ll.append(10)
    ll.append('10')
    ll.append('ten')
    ll.prepend(20)
    expect(ll.head.value).toEqual(20)
    expect(ll.tail.value).toEqual('ten')
    expect(ll.size).toEqual(4)

  })
  test('delete', () => {
    const ll = new LinkedList()
    ll.append(10)
    ll.append('10')
    ll.append('ten')
    ll.prepend(20)
    ll.delete(20)
    expect(ll.head.value).toEqual(10)
    expect(ll.tail.value).toEqual('ten')
    expect(ll.size).toEqual(3)
  })
  test('toArray', () => {
    const ll = new LinkedList()
    ll.append(10)
    ll.append('10')
    ll.append('ten')
    ll.prepend(20)
    expect(ll.toArray()).toEqual([20,10,'10','ten'])
  })
})